# Swan Teleco Project

## Importing the modules

In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

from sklearn import metrics
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier as DT
from sklearn.ensemble import RandomForestClassifier as RF
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

In [2]:
df = pd.read_csv("C:/Users/osman/Downloads/1_-_Project_Data.csv")

In [3]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,Competitor had better devices

In [4]:
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Reason'],
      dtype='object')

In [5]:
df.shape

(7043, 31)

In [6]:
df.isnull().sum() # No nulls

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Reason         5174
dtype: int64

In [7]:
df.dtypes

CustomerID            object
Count                  int64
Country               object
State                 object
City                  object
Zip Code               int64
Lat Long              object
Latitude             float64
Longitude            float64
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges         object
Churn Label           object
Churn Value            int64
Churn Reason          object
dtype: object

In [8]:
# Set 'CustomerID' as the index of df 
df = df.set_index('CustomerID')
df.head()

,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,...,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Reason
CustomerID,,,,,,,,,,,,,,,,,,,,,
3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,No,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,Competitor made better offer
9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,Moved
9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,Moved
7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,Moved
0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,No,...,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,Competitor had better devices

## Train Test Splitting

In [9]:
y = df['Churn Value']  # Extract the target column
X = df.drop(columns=['Churn Value'])  # Drop the target column from the DataFrame

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
X_train.head()

,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,...,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Reason
CustomerID,,,,,,,,,,,,,,,,,,,,,
9571-EDEBV,1,United States,California,San Diego,92119,"32.802959, -117.027095",32.802959,-117.027095,Male,No,...,No,Yes,Yes,One year,Yes,Credit card (automatic),98.65,6962.85,No,NaN
7562-GSUHK,1,United States,California,Jamestown,95327,"37.84771, -120.486589",37.847710,-120.486589,Female,No,...,No,No,Yes,Month-to-month,Yes,Credit card (automatic),93.20,1573.7,Yes,Competitor made better offer
2325-WINES,1,United States,California,Littlerock,93543,"34.505273, -117.955054",34.505273,-117.955054,Female,No,...,No,Yes,Yes,One year,Yes,Credit card (automatic),104.05,3416.85,No,NaN
9381-NDKME,1,United States,California,El Monte,91731,"34.079934, -118.046695",34.079934,-118.046695,Female,Yes,...,No,No,Yes,Month-to-month,Yes,Credit card (automatic),40.65,933.3,Yes,Limited range of services
2164-SOQXL,1,United States,California,Los Angeles,90043,"33.988543, -118.334081",33.988543,-118.334081,Female,No,...,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,20.05,406.05,No,NaN

In [11]:
y.head()

CustomerID
3668-QPYBK    1
9237-HQITU    1
9305-CDSKC    1
7892-POOKP    1
0280-XJGEX    1
Name: Churn Value, dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder
def train_encode(df):
    le = LabelEncoder()
    le.fit(df['City'])
    return le
le = train_encode(X_train)

In [13]:
def cleaning_fct(df):
    df['Gender'] = df['Gender'].map({'Female':0, 'Male':1})
    df['Senior Citizen'] = df['Senior Citizen'].map({'No':0, 'Yes':1})
    df['Partner'] = df['Partner'].map({'No':0, 'Yes':1})
    df['Dependents'] = df['Dependents'].map({'No':0, 'Yes':1})
    df['Phone Service'] = df['Phone Service'].map({'No':0, 'Yes':1})
    df['Multiple Lines'] = df['Multiple Lines'].map({'No':0, 'Yes':1, 'No phone service':2})
    df['Internet Service'] = df['Internet Service'].map({'DSL':0, 'Fiber optic':1, 'No':2})
    df['Online Security'] = df['Online Security'].map({'No':0, 'Yes':1, 'No internet service':2})
    df['Online Backup'] = df['Online Backup'].map({'No':0, 'Yes':1, 'No internet service':2})
    df['Device Protection'] = df['Device Protection'].map({'No':0, 'Yes':1, 'No internet service':2})
    df['Tech Support'] = df['Tech Support'].map({'No':0, 'Yes':1, 'No internet service':2})
    df['Streaming TV'] = df['Streaming TV'].map({'No':0, 'Yes':1, 'No internet service':2})
    df['Streaming Movies'] = df['Streaming Movies'].map({'No':0, 'Yes':1, 'No internet service':2})
    df['Contract'] = df['Contract'].map({'Month-to-month':0, 'Two year':1, 'One year':2})
    df['Paperless Billing'] = df['Paperless Billing'].map({'No':0, 'Yes':1})
    df['Payment Method'] = df['Payment Method'].map({'Mailed check':0, 'Electronic check':1, 'Bank transfer (automatic)':2, 'Credit card (automatic)':3})

    df['City Number'] = le.transform(df['City'])

    cols = ['City Number', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges']
    df = df[cols]

    return df

In [14]:
X_train_cl=cleaning_fct(X_train)

In [15]:
X_train_cl

,City Number,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,...,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges
CustomerID,,,,,,,,,,,,,,,,,,,,,
9571-EDEBV,869,92119,"32.802959, -117.027095",32.802959,-117.027095,1,0,1,0,71,...,0,1,0,1,1,2,1,3,98.65,6962.85
7562-GSUHK,462,95327,"37.84771, -120.486589",37.847710,-120.486589,0,0,0,0,16,...,1,1,0,0,1,0,1,3,93.20,1573.7
2325-WINES,541,93543,"34.505273, -117.955054",34.505273,-117.955054,0,0,0,0,32,...,1,1,0,1,1,2,1,3,104.05,3416.85
9381-NDKME,292,91731,"34.079934, -118.046695",34.079934,-118.046695,0,1,1,0,24,...,0,1,0,0,1,0,1,3,40.65,933.3
2164-SOQXL,562,90043,"33.988543, -118.334081",33.988543,-118.334081,0,0,1,1,20,...,2,2,2,2,2,0,0,0,20.05,406.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8216-AZUUZ,872,94118,"37.781304, -122.461522",37.781304,-122.461522,0,0,1,1,42,...,0,1,1,1,1,1,1,1,100.40,4303.65
5006-MXVRN,479,95328,"37.555631, -120.911653",37.555631,-120.911653,0,0,0,0,39,...,2,2,2,2,2,1,0,3,20.70,762.45
4804-NCPET,196,95422,"38.965804, -122.631779",38.965804,-122.631779,1,0,1,1,19,...,2,2,2,2,2,1,0,0,20.20,387.4
2878-DHMIN,855,95833,"38.619049, -121.517552",38.619049,-121.517552,1,0,1,1,35,...,2,2,2,2,2,2,0,1,19.90,666
7774-OJSXI,958,96150,"38.911577, -120.106169",38.911577,-120.106169,1,0,0,0,31,...,1,1,0,1,1,2,1,1,103.45,3066.45

In [16]:
X_train_cl[['Zip Code']].nunique()

Zip Code    1652
dtype: int64

In [17]:
X_train_cl['Monthly Charges'].isnull().sum()

0

In [18]:
print(df['Total Charges'].unique())

['108.15' '151.65' '820.5' ... '7362.9' '346.45' '6844.5']

In [19]:
X_train_cl.columns # Columns in X_train

Index(['City Number', 'Zip Code', 'Lat Long', 'Latitude', 'Longitude',
       'Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months',
       'Phone Service', 'Multiple Lines', 'Internet Service',
       'Online Security', 'Online Backup', 'Device Protection', 'Tech Support',
       'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charges', 'Total Charges'],
      dtype='object')

## Feature engineering

In [20]:
def feature_eng(df):
    
    # Create a copy of the data
    df = df.copy()
    
    # Drop longitude and latitude and Zip Code columns 
    df = df.drop(columns=['Longitude', 'Latitude', 'Lat Long', 'Zip Code'])
    
    # Convert the 'Total Charges' column to float
    df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')
    
    # Fill null values in Total Charges to 0
    df['Total Charges'].fillna(0, inplace=True)
    
    # Add aditional charges column 
    df['Additional charges'] = df['Total Charges'] - (df['Monthly Charges'] * df['Tenure Months'])
    
    return df

In [21]:
X_train_fe = feature_eng(X_train_cl)

In [22]:
null_indices = X_train_fe[X_train_fe['Total Charges'].isnull()].index
null_indices

Index([], dtype='object', name='CustomerID')

In [23]:
X_train_fe = feature_eng(X_train_cl)
X_train_fe.dtypes

City Number             int32
Gender                  int64
Senior Citizen          int64
Partner                 int64
Dependents              int64
Tenure Months           int64
Phone Service           int64
Multiple Lines          int64
Internet Service        int64
Online Security         int64
Online Backup           int64
Device Protection       int64
Tech Support            int64
Streaming TV            int64
Streaming Movies        int64
Contract                int64
Paperless Billing       int64
Payment Method          int64
Monthly Charges       float64
Total Charges         float64
Additional charges    float64
dtype: object

## Random Forest Model

In [24]:
clf = RF(criterion = 'entropy',
        max_depth=5,
        n_estimators = 10)
clf.fit(X_train_fe, y_train)

RandomForestClassifier(criterion='entropy', max_depth=5, n_estimators=10)

In [25]:
X_test_cl=cleaning_fct(X_test)
X_test_fe=feature_eng(X_test_cl)

In [26]:
X_test_fe

,City Number,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,...,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Additional charges
CustomerID,,,,,,,,,,,,,,,,,,,,,
2189-WWOEW,473,0,0,0,0,15,1,0,1,0,...,0,0,0,1,0,1,2,85.90,1269.55,-18.95
2446-ZKVAF,972,1,0,1,0,18,1,1,0,0,...,0,0,0,0,0,0,3,56.80,1074.65,52.25
4986-MXSFP,881,0,0,0,0,2,1,0,2,2,...,2,2,2,2,0,1,0,20.00,40.90,0.90
5868-YWPDW,931,1,1,1,0,6,1,0,1,0,...,0,0,0,1,0,1,1,84.20,519.15,13.95
9412-GHEEC,662,1,0,0,0,40,1,1,1,0,...,1,1,1,1,0,0,2,104.80,4131.95,-60.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5553-AOINX,216,0,1,1,1,66,1,1,1,0,...,1,0,1,1,2,1,1,104.90,6891.45,-31.95
9866-QEVEE,632,1,0,0,0,19,1,1,1,0,...,0,0,0,1,0,1,2,86.00,1532.45,-101.55
0139-IVFJG,455,0,0,1,0,2,1,0,1,1,...,0,0,1,0,0,0,1,90.35,190.50,9.80
5153-LXKDT,244,1,0,1,1,68,1,1,1,1,...,1,0,1,1,1,1,1,110.20,7467.50,-26.10
6543-XRMYR,972,0,1,0,0,30,1,1,1,0,...,0,0,1,1,0,1,1,99.70,2967.35,-23.65

In [27]:
print(f'The training accuracy is :{clf.score(X_train_fe, y_train)}')
print(f'The testing accuracy is :{clf.score(X_test_fe, y_test)}')

The training accuracy is :0.8077742279020235
The testing accuracy is :0.7906316536550745

In [29]:
y_pred = clf.predict(X_test_fe)
metrics.confusion_matrix(y_test, y_pred)

array([[934,  75],
       [220, 180]], dtype=int64)

In [ ]:
Test_pred = pd.DataFrame()
Test_pred['Actual'] = y_test
Test_pred['Predicted'] = y_pred
Test_pred.head()